### PR TITLE
README.md updates

### PR DESCRIPTION
**Pull request by kendaleiv**

### CODE REVIEW

**Comment by dsagang** [comment]
Here https://github.com/ritterim/angular2-bank/blob/master/README.md#core-feature-goals, I think it should be to deposit, withdraw ...

**Comment by kendaleiv** [comment]
Ah, good catch. It's wrong in code/tests too. Are you interested in finding and updating them in addition to the README.md -- or should I handle it?

**Comment by dsagang** [comment]
It does not matter to me.

**Comment by kendaleiv** [comment]
I updated it in PR #13.

**Pull request merged**
